---
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Start Apache on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == 'Ubuntu'

    - name: Enable Apache on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Start Apache on CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'CentOS'

    - name: Enable Apache on CentOS
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == 'CentOS'

    - name: Install Apache on Amazon Linux
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == 'Amazon'

    - name: Start Apache on Amazon Linux
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'Amazon'

    - name: Enable Apache on Amazon Linux
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == 'Amazon'
...