---
- name: Install Git, Java 11, Maven and HTTPD
  hosts: g1
  become: yes

  tasks:
    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: ansible_distribution == 'Amazon'

    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
    
    - name: Install Java on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Java on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Java on Amazon Linux
      dnf:
        name: java-11-amazon-corretto
        state: present
      when: ansible_distribution == 'Amazon'
  
    - name: Install Maven on Ubuntu
      apt:
        name: maven
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Maven on CentOS
      yum:
        name: maven
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Maven on Amazon Linux
      dnf:
        name: maven
        state: present
      when: ansible_distribution == 'Amazon'
    
    - name: Install Apache on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Start Apache on Ubuntu
      service:
        name: apache2
        state: started
      when: ansible_distribution == 'Ubuntu'

    - name: Enable Apache on Ubuntu
      service:
        name: apache2
        enabled: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Install Apache on CentOS
      yum:
        name: httpd
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Start Apache on CentOS
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'CentOS'

    - name: Enable Apache on CentOS
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == 'CentOS'

    - name: Install Apache on Amazon Linux
      dnf:
        name: httpd
        state: present
      when: ansible_distribution == 'Amazon'

    - name: Start Apache on Amazon Linux
      service:
        name: httpd
        state: started
      when: ansible_distribution == 'Amazon'

    - name: Enable Apache on Amazon Linux
      service:
        name: httpd
        enabled: yes
      when: ansible_distribution == 'Amazon'
...