---
- name: Transfer WAR files
  hosts: g1
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /path/to/checkout/target/
        dest: /opt/tomcat/webapps/
      delegate_to: g2
...