---
- name: Move and Deploy WAR files
  hosts: g1
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator/target/
        state: directory
      become: yes

    - name: Find WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/target/
        patterns: "*.war"
      register: war_files

    - name: Copy WAR files to Ansible Controller
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /home/centos/mid-project-calculator/
        flat: yes
      with_items: "{{ war_files.files }}"
      become: yes

- name: Move and Deploy WAR files
  hosts: g2
  tasks:
    - name: Find WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/
        patterns: "*.war"
      register: war_files

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory
      become: yes

    - name: Copy WAR files to destination servers
      ansible.builtin.copy:
        src: /home/centos/mid-project-calculator/
        dest: /opt/tomcat/webapps/
      with_items: "{{ war_files.files }}"
      become: yes
      become_user: centos
    
    - name: Debug copied files
      debug:
        var: item.path
      with_items: "{{ war_files.files }}"
      become: yes

    - name: Debug destination directory contents
      ansible.builtin.shell: ls -l /opt/tomcat/webapps/
      become: yes

    - name: Debug Destination Directory Permissions
      shell: stat -c "%a %n" /opt/tomcat/webapps/
      become: yes
...