---
- name: Stash war files
  hosts: g1, g2
  become: yes

  roles:
    - stash
  
  tasks:
    - name: Copy .war files to destination servers
      synchronize:
        src: "{{ item.path }}"
        dest: /opt/tomcat/webapps
      delegate_to: "{{ item.ansible_host }}"
      with_items: "{{ war_files.files }}"
      when: war_files.matched > 0
...