---
- name: Move and Deploy WAR files
  hosts: g1
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator/target/
        state: directory
      become: yes

    - name: Find WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/target/
        patterns: "*.war"
      register: war_files

    - name: Copy WAR files to Ansible Controller
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /home/centos/mid-project-calculator/
        flat: yes
      with_items: "{{ war_files.files }}"
      become: yes

- name: Move and Deploy WAR files
  hosts: g2
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator/
        state: directory
      become: yes

    - name: Find WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/
        patterns: "*.war"
      register: war_files

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory
      become: yes

    - name: Copy WAR files to destination servers
      ansible.builtin.copy:
        src: "/home/centos/mid-project-calculator/{{ item.path | basename }}"
        dest: "/opt/tomcat/webapps/{{ item.path | basename }}"
      with_items: "{{ war_files.files }}"
      when: "'g2' in inventory_hostname or 'g2' in groups"
      become: yes

    - name: Debug Destination Directory Permissions
      shell: stat -c "%a %n" /opt/tomcat/webapps/
...