---
- name: Transfer WAR files
  hosts: g2
  tasks:
    - name: Copy WAR files to a temporary directory
      ansible.builtin.copy:
        src: /path/to/checkout/target/
        dest: /tmp/app.war
      become: yes

- name: Deploy WAR files to another server
  hosts: g2
  tasks:
    - name: Transfer WAR files to destination server
      ansible.builtin.copy:
        src: /tmp/app.war
        dest: /opt/tomcat/webapps/
      become: yes
...