---
- name: Transfer WAR files
  hosts: g1
  tasks:
    - name: Copy WAR files to a temporary directory
      ansible.builtin.copy:
        src: "/path/to/checkout/target/*.war"
        dest: /tmp/
      become: yes

- name: Deploy WAR files to another server
  hosts: g2
  tasks:
    - name: Transfer WAR files to destination server
      ansible.builtin.copy:
        src: "/tmp/*.war"
        dest: /opt/tomcat/webapps/
      become: yes
...