---
- name: Transfer WAR files
  hosts: g1
  tasks:
    - name: Synchronize WAR files to destination
      ansible.builtin.synchronize:
        src: /path/to/checkout/target/
        dest: /opt/tomcat/webapps/
        rsync_opts: --include='*.war' --exclude='*'

- name: Ensure Tomcat directory exists
  hosts: g2
  tasks:
    - name: Ensure Tomcat directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory
      mode: '0755'
...