---
- name: Move and Deploy WAR files
  hosts: g1
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator/target/
        state: directory
      become: yes

    - name: Stash WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/target/
        patterns: "*.war"
      register: war_files

    - name: Copy WAR files to Ansible Controller
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "/home/centos/mid-project-calculator/{{ item.path | basename }}"
        flat: yes
      with_items: "{{ war_files.files }}"
      become: yes
...