---
- name: Remove Previous WAR files from Ansible Controller
  hosts: localhost  # Assuming the Ansible controller is localhost
  gather_facts: false  # No need to gather facts for the localhost
  tasks:
    - name: Find Previous WAR files on Ansible Controller
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/build/
        patterns: "*.war"
      register: previous_war_files

    - name: Remove Previous WAR files from Ansible Controller
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
        force: yes
      with_items: "{{ previous_war_files.files }}"
      when: previous_war_files.matched > 0  # Only remove if there are previous files
      become: yes
...