---
- name: Copy File to Another Server
  hosts: g1
  tasks:
    - name: Debug - List files in the source directory
      ansible.builtin.shell:
        cmd: "ls -l /home/centos/mid-project-calculator/target/*.war"
      register: ls_output
      changed_when: false

    - debug:
        var: ls_output.stdout_lines

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: /tmp/fetched_files/
        state: directory
    
    - name: Copy files to control node
      ansible.builtin.shell:
        cmd: "rsync -a /home/centos/mid-project-calculator/target/*.war /tmp/fetched_files/"
      args:
        executable: /bin/bash
      register: rsync_output

    - name: Set global variable for fetched files
      ansible.builtin.set_fact:
        fetched_files_path: "/tmp/fetched_files"
      when: rsync_output.changed

    - name: Debug - List files in the control node directory
      ansible.builtin.shell:
        cmd: "ls -l /tmp/fetched_files"
      changed_when: false

    - debug:
        var: rsync_output

- name: Template and Copy File to Destination Server
  hosts: g2
  tasks:
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory

    - name: Copy files to destination server
      ansible.builtin.copy:
        src: "{{ fetched_files_path }}/{{ item | basename }}"
        dest: "/path/to/destination/directory/{{ item | basename }}"
      with_fileglob:
        - "{{ fetched_files_path }}/*.war"

    - name: Clean up temporary files on the control node
      ansible.builtin.file:
        path: "{{ fetched_files_path }}"
        state: absent
      when: fetched_files_path is defined
...