---
- name: Copy File to Another Server
  hosts: g1
  tasks:
    - name: Debug - List files in the source directory
      ansible.builtin.shell:
        cmd: "ls -l /home/centos/mid-project-calculator/target/*.war"
      register: ls_output
      changed_when: false

    - debug:
        var: ls_output.stdout_lines

    - name: Ensure the target directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator
        state: directory

    - name: Copy files to control node
      ansible.builtin.shell:
        cmd: "rsync -a /home/centos/mid-project-calculator/target/*.war /home/centos/mid-project-calculator/"
      args:
        executable: /bin/bash
      register: rsync_output

    - name: Set global variable for fetched files
      ansible.builtin.set_fact:
        fetched_files_path: "/home/centos/mid-project-calculator"
      when: rsync_output.changed

    - name: Debug - List files in the control node directory
      ansible.builtin.shell:
        cmd: "ls -l /home/centos/mid-project-calculator"
      changed_when: false

    - debug:
        var: rsync_output

- name: Template and Copy File to Destination Server
  hosts: g2
  tasks:
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory

    - name: Copy files to destination server
      ansible.builtin.copy:
        src: "/home/centos/mid-project-calculator/{{ item | basename }}"
        dest: "/opt/tomcat/webapps/{{ item | basename }}"
      with_fileglob:
        - "/home/centos/mid-project-calculator/*.war"
...