---
- name: Copy File to Another Server
  hosts: g1
  tasks:
    - name: Ensure source directory exists
      ansible.builtin.file:
        path: /home/centos/mid-project-calculator/target/
        state: directory
      become: yes

    - name: Find WAR files
      ansible.builtin.find:
        paths: /home/centos/mid-project-calculator/target/
        patterns: "*.war"
      register: war_files

    - name: Copy WAR files to Ansible Controller
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: /home/centos/mid-project-calculator/
        flat: yes
      with_items: "{{ war_files.files }}"
      become: yes

- name: Template and Copy File to Destination Server
  hosts: g2
  tasks:
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory

    - name: Copy files to destination server
      ansible.builtin.copy:
        src: "/home/centos/mid-project-calculator/{{ item | basename }}"
        dest: "/opt/tomcat/webapps/{{ item | basename }}"
      with_fileglob:
        - "/home/centos/mid-project-calculator/*.war"
      become: yes
...