---
    - name: Download and extract Apache Tomcat 11
      shell: "wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz -O /opt/apache-tomcat-9.0.56.tar.gz"
      args:
        creates: /opt/apache-tomcat-9.0.56.tar.gz  # Skip download if already present

    - name: Extract the Tomcat archive
      command: "tar -xf /opt/apache-tomcat-9.0.56.tar.gz -C /opt/"

    - name: Rename Tomcat directory
      command: "mv /opt/apache-tomcat-9.0.56 /opt/tomcat"

    - name: Set environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/tomcat"
        create: yes

    - name: Start Tomcat service
      command: "/opt/tomcat/bin/startup.sh"
...