---
    - name: Download and extract Apache Tomcat 11
      shell: "wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz -O /opt/apache-tomcat-7.0.94.tar.gz"
      args:
        creates: /opt/apache-tomcat-7.0.94.tar.gz  # Skip download if already present

    - name: Extract the Tomcat archive
      command: "tar xvf apcahe-tomcat-7.0.94.tar.gz -C /opt/"

    - name: Rename Tomcat directory
      command: "mv /opt/apache-tomcat-7.0.94/* /opt/tomcat"
      args:
        creates: /opt/tomcat/bin/startup.sh  # Skip if files are already present

    - name: Set environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/tomcat"
        create: yes
    
    - name: System CTL
      command: systemctl daemon-reload
      become: yes

    - name: Start Tomcat service
      command: "/opt/tomcat/bin/startup.sh"  
...