---
    - name: Download and extract Apache Tomcat 11
      shell: "wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz -O /opt/apache-tomcat-7.0.94.tar.gz"
      args:
        creates: /opt/apache-tomcat-7.0.94.tar.gz  # Skip download if already present

    - name: Extract the Tomcat archive
      command: "tar xvf apcahe-tomcat-7.0.94.tar.gz"
    
    - name: System CTL
      command: systemctl daemon-reload
      become: yes

    - name: Start Tomcat service
      command: "/home/centos/apache-tomcat-7.0.94/bin/startup.sh"  
...