---
    - name: Check if Apache Tomcat archive already exists
      ansible.builtin.stat:
        path: "/opt/apache-tomcat-7.0.94.tar.gz"
      register: tomcat_archive

    - name: Download Apache Tomcat 7.0.94 if not present
      ansible.builtin.get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.94/bin/apache-tomcat-7.0.94.tar.gz"
        dest: "/opt/apache-tomcat-7.0.94.tar.gz"
      when: not tomcat_archive.stat.exists

    - name: Extract the Tomcat archive
      ansible.builtin.command: "tar xvf /opt/apache-tomcat-7.0.94.tar.gz -C /opt/"
      args:
        creates: /opt/apache-tomcat-7.0.94/  # Skip extraction if directory already present

    - name: Move Tomcat contents to /opt/tomcat
      ansible.builtin.command: "mv /opt/apache-tomcat-7.0.94/* /opt/tomcat/"
      args:
        creates: /opt/tomcat/bin/startup.sh  # Skip if files are already present

    - name: Set environment variables
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/tomcat"
        create: yes

    - name: System CTL
      ansible.builtin.command: "systemctl daemon-reload"
      become: yes
      when: "'systemd' in ansible_playbook_python | lower and ansible_distribution_major_version|int >= 7"
  
  - name: Start Tomcat service with systemd
    ansible.builtin.systemd:
      name: tomcat
      state: started
    become: yes
    when: "'systemd' in ansible_playbook_python | lower"

    - name: Start Tomcat service
      ansible.builtin.command: "/opt/tomcat/bin/startup.sh"
      become: yes
      when: "'systemd' not in ansible_playbook_python | lower"
...