---
    - name: Download and extract Apache Tomcat 11
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-11/v11.0.13/bin/apache-tomcat-11.0.13.tar.gz"
        dest: "/opt/"
        mode: 0755

    - name: Extract the Tomcat archive
      command: "tar -xf /opt/apache-tomcat-11.0.13.tar.gz -C /opt/"

    - name: Rename Tomcat directory
      command: "mv /opt/apache-tomcat-11.0.13 /opt/tomcat"

    - name: Set environment variables
      lineinfile:
        path: "/etc/environment"
        line: "CATALINA_HOME=/opt/tomcat"
        create: yes

    - name: Start Tomcat service
      command: "/opt/tomcat/bin/startup.sh"
...