---
    - name: Ensure the destination directory exists
      ansible.builtin.file:
        path: /opt/tomcat/webapps/
        state: directory

    - name: Copy files to destination server
      ansible.builtin.copy:
        src: "/home/centos/mid-project-calculator/{{ item | basename }}"
        dest: "/opt/tomcat/webapps/{{ item | basename }}"
      with_fileglob:
        - "/home/centos/mid-project-calculator/*.war"
      become: yes
...