---
- name: Install Git, Java 11, Maven and HTTPD
  hosts: g1
  become: yes

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
    
    - name: Install Java on Ubuntu
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Java on CentOS
      yum:
        name: java-11-openjdk
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Java on Amazon Linux
      dnf:
        name: java-11-amazon-corretto
        state: present
      when: ansible_distribution == 'Amazon'
...