---
    - name: Install Git on Ubuntu
      apt:
        name: git
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Install Git on CentOS
      yum:
        name: git
        state: present
      when: ansible_distribution == 'CentOS'

    - name: Install Git on Amazon Linux
      dnf:
        name: git
        state: present
      when: ansible_distribution == 'Amazon'
...