---
    - name: Install wget (if not already installed)
      yum:
        name: wget
        state: present  # Ensure wget is installed
      become: yes

    - name: Download Apache Maven
      shell: "wget https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz -O /tmp/apache-maven-3.9.5-bin.tar.gz"
      args:
        creates: /tmp/apache-maven-3.9.5-bin.tar.gz  # Skip download if already present

    - name: Extract Maven archive
      shell: "tar xzf /tmp/apache-maven-3.9.5-bin.tar.gz -C /opt"
      args:
        creates: /opt/apache-maven-3.9.5  # Skip extraction if already present
      become: yes

    - name: Create symbolic link to Maven
      file:
        src: /opt/apache-maven-3.9.5
        dest: /opt/maven
        state: link
        force: yes
      become: yes

    - name: Set Maven environment variables
      lineinfile:
        path: /etc/profile.d/maven.sh
        create: yes
        line: |
          export JAVA_HOME=/usr/lib/jvm/jre-openjdk
          export M2_HOME=/opt/maven
          export MAVEN_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH} 
      notify: reload shell environment
      args:
        create: /etc/profile.d/maven.sh  # Skip if already present
      become: yes

    - command: chmod +x /etc/profile.d/maven.sh
      become: yes

    - command: source /etc/profile.d/maven.sh
      become: yes
...